from pathlib import Path

Import("env")

# The C6 firmware must always match the ESP-Hosted implementation compiled
# into the P4 app.  The Arduino platform package ships the matching image, so
# generate a tiny assembly include that folds that exact binary into the P4
# application image.  This avoids asking an old/broken C6 to fetch its own
# replacement over DNS/HTTPS.
if env.subst("$PIOENV") in ("jc4880p443", "waveshare-p4-4b"):
    project_dir = Path(env.subst("$PROJECT_DIR"))
    libs_dir = Path(env.PioPlatform().get_package_dir("framework-arduinoespressif32-libs"))
    firmware = libs_dir / "hosted" / "esp32c6-v2.12.11.bin"
    if not firmware.is_file():
        raise RuntimeError(f"ESP-Hosted C6 firmware not found: {firmware}")

    # The generated absolute path belongs only to this build machine; it is
    # deliberately regenerated every build from the installed platform package.
    escaped_firmware = str(firmware).replace("\\", "\\\\").replace('"', '\\"')
    target = project_dir / "include" / "generated" / "hosted_c6_firmware_asm.h"
    target.parent.mkdir(parents=True, exist_ok=True)
    content = f'''#pragma once

// Generated by scripts/embed_hosted_firmware.py. Do not edit by hand.
asm(R"WLED_HOSTED_C6(
.section .rodata.embedded,"a",@progbits
.global wled_hosted_c6_firmware_start
.global wled_hosted_c6_firmware_end
.balign 4
wled_hosted_c6_firmware_start:
.incbin "{escaped_firmware}"
wled_hosted_c6_firmware_end:
)WLED_HOSTED_C6");
'''
    if not target.exists() or target.read_text() != content:
        target.write_text(content)
